#!/usr/bin/env python3
"""
Turn a comic's segmented panels (from segment_panels.py) into a
descriptive transcript: a plain-English, panel-by-panel account of what's
drawn (characters, poses, actions) plus a verbatim read of any
speech-bubble/handwritten text -- distinct from the dialogue-only
`transcript` field already in `../../funnyguycomics` (which the original
author typed by hand and which drops the visual half of the joke).

Runs entirely against a local Ollama vision model (GPU-accelerated via
Ollama's own CUDA backend, falls back to CPU if no GPU is available) --
no cloud API calls, no extra Python deps beyond the standard library,
since this script only does HTTP + base64 + file I/O and lets Ollama do
the actual inference. Requires `ollama serve` running locally with the
model already pulled (`ollama pull qwen2.5vl:7b`).

Run with plain system python3 (stdlib only, no venv needed):
    python3 describe_panels.py
    python3 describe_panels.py --comic 001_the_funny_guy
    python3 describe_panels.py --limit 5

Input:  ../output/panels/<slug>/panel_NN.png        (from segment_panels.py)
        ../output/panels/segmentation_manifest.csv  (to skip failed comics)
Output: ../output/transcripts/<slug>.md
        ../output/transcripts/manifest.csv
"""
import argparse
import base64
import csv
import json
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent
PANELS_DIR = REPO_ROOT / "output" / "panels"
SEGMENTATION_MANIFEST = PANELS_DIR / "segmentation_manifest.csv"
OUT_DIR = REPO_ROOT / "output" / "transcripts"

OLLAMA_URL = "http://localhost:11434/api/generate"
MODEL = "qwen2.5vl:7b"
REQUEST_TIMEOUT = 120
MAX_RETRIES = 2

PROMPT = (
    "This is one panel from a crude, hand-drawn stick-figure webcomic "
    "called Funny Guy. Describe what's visually happening in this panel "
    "in 1-3 plain sentences: the characters (use their handwritten name "
    "labels if any are visible, otherwise describe them physically), "
    "their actions/poses/expressions, and any notable visual gag. Then, "
    "if there is any speech-bubble or handwritten text in the panel, "
    "transcribe it verbatim in quotes -- if there's none, say so. Be "
    "concise and literal, don't editorialize or guess at plot beyond "
    "what's drawn."
)


def eligible_slugs():
    """Comics that segment_panels.py actually produced panels for."""
    if not SEGMENTATION_MANIFEST.exists():
        print(f"no segmentation manifest at {SEGMENTATION_MANIFEST} -- run segment_panels.py first", file=sys.stderr)
        sys.exit(1)
    slugs = []
    with SEGMENTATION_MANIFEST.open() as f:
        for row in csv.DictReader(f):
            if row["status"] in ("ok", "ok_low_confidence"):
                slugs.append(row["comic"])
    return slugs


def describe_panel(img_path: Path) -> str:
    b64 = base64.b64encode(img_path.read_bytes()).decode()
    payload = {
        "model": MODEL,
        "prompt": PROMPT,
        "images": [b64],
        "stream": False,
    }
    req = urllib.request.Request(
        OLLAMA_URL,
        data=json.dumps(payload).encode(),
        headers={"Content-Type": "application/json"},
    )
    last_err = None
    for attempt in range(1, MAX_RETRIES + 1):
        try:
            with urllib.request.urlopen(req, timeout=REQUEST_TIMEOUT) as resp:
                result = json.loads(resp.read())
            return result["response"].strip()
        except (urllib.error.URLError, TimeoutError, KeyError, json.JSONDecodeError) as e:
            last_err = e
            if attempt < MAX_RETRIES:
                time.sleep(2)
    raise RuntimeError(f"ollama request failed after {MAX_RETRIES} attempts: {last_err}")


def describe_comic(slug: str) -> tuple[int, int]:
    """Returns (n_panels, n_failed)."""
    comic_dir = PANELS_DIR / slug
    panels = sorted(comic_dir.glob("panel_*.png"))
    if not panels:
        return 0, 0

    lines = [f"# {slug} -- descriptive transcript", "", f"_generated by describe_panels.py, model={MODEL}_", ""]
    n_failed = 0
    for n, panel_path in enumerate(panels, start=1):
        try:
            description = describe_panel(panel_path)
        except RuntimeError as e:
            description = f"(description failed: {e})"
            n_failed += 1
        lines.append(f"**Panel {n}.** {description}")
        lines.append("")

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    (OUT_DIR / f"{slug}.md").write_text("\n".join(lines))
    return len(panels), n_failed


def check_ollama_ready():
    try:
        with urllib.request.urlopen("http://localhost:11434/api/version", timeout=5) as resp:
            json.loads(resp.read())
    except (urllib.error.URLError, TimeoutError) as e:
        print(f"can't reach ollama at {OLLAMA_URL} -- is `ollama serve` running? ({e})", file=sys.stderr)
        sys.exit(1)


def main():
    global MODEL
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--comic", default=None, help="process a single comic by slug")
    parser.add_argument("--limit", type=int, default=None, help="only process the first N comics")
    parser.add_argument("--model", default=MODEL, help=f"ollama model to use (default: {MODEL})")
    parser.add_argument("--force", action="store_true", help="re-describe comics that already have a transcript")
    args = parser.parse_args()

    MODEL = args.model

    check_ollama_ready()

    slugs = eligible_slugs()
    if args.comic:
        slugs = [s for s in slugs if s == args.comic]
        if not slugs:
            print(f"no eligible (segmented) comic found matching slug {args.comic!r}", file=sys.stderr)
            sys.exit(1)
    if not args.force:
        slugs = [s for s in slugs if not (OUT_DIR / f"{s}.md").exists()]
    if args.limit:
        slugs = slugs[: args.limit]

    if not slugs:
        print("nothing to do -- all eligible comics already have transcripts (use --force to redo)")
        return

    manifest_rows = []
    t_start = time.time()
    for i, slug in enumerate(slugs):
        t0 = time.time()
        n_panels, n_failed = describe_comic(slug)
        dt = time.time() - t0
        status = "ok" if n_failed == 0 else ("partial" if n_failed < n_panels else "failed")
        manifest_rows.append({"comic": slug, "n_panels": n_panels, "n_failed": n_failed, "status": status, "seconds": f"{dt:.1f}"})
        print(f"[{i + 1}/{len(slugs)}] {slug}: {n_panels} panels, {n_failed} failed ({dt:.1f}s)", file=sys.stderr)

    manifest_path = OUT_DIR / "manifest.csv"
    existing_rows = []
    if manifest_path.exists():
        with manifest_path.open() as f:
            existing_rows = [r for r in csv.DictReader(f) if r["comic"] not in {row["comic"] for row in manifest_rows}]
    with manifest_path.open("w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=["comic", "n_panels", "n_failed", "status", "seconds"])
        writer.writeheader()
        writer.writerows(existing_rows + manifest_rows)

    print(f"described {len(slugs)} comics in {time.time() - t_start:.0f}s, manifest at {manifest_path}")


if __name__ == "__main__":
    main()
