#!/usr/bin/env python3
"""
Proof-of-concept: use the layered originals in Raw/*.psd (see
references/remix_material_audit.md) to actually swap out a panel's
dialogue, not just re-caption over it. Every panel here is a hand-picked
real speech bubble confirmed (by hiding the layer and diffing against the
full composite) to be its own separate Photoshop type layer sitting over
otherwise-untouched hand-drawn art -- not every panel in every comic has
this, most dialogue is baked into the scanned pencil layer and can't be
touched this way, see the audit doc.

Rather than trying to redraw new text inside the original speech-bubble
shape (would need to match a hand-lettering font we don't have and don't
know), each remix hides the original type layer(s) -- leaving a real,
undoctored blank bubble on real hand-drawn 2000s-2001s art -- crops to
just that panel, and adds the new line as a caption card underneath,
reusing make_short.py's exact letterboxing/caption styling so these look
like the same series, just with a different joke.

New lines are hand-written for this test batch (references/remix_style.md
tone), not generated by a script -- picking which panels are even
swappable already took manual PSD inspection per comic, so there's no
"generate lines automatically" step to plug in yet.

Run with the ComfyUI venv's interpreter (has PIL, psd_tools):
    /home/adamyoung/src/ComfyUI/.venv/bin/python3 remix_psd.py

Input:  /mnt/creative/projects/funnyguy/Raw/<slug>.psd
Output: ../output/remixes/<name>.mp4
"""
import subprocess
import sys
import tempfile
from pathlib import Path

from psd_tools import PSDImage

SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR))
from make_short import CANVAS, FPS, ZOOM_END, letterbox  # reuse the established look

RAW_DIR = Path("/mnt/creative/projects/funnyguy/Raw")
OUT_DIR = SCRIPT_DIR.parent / "output" / "remixes"

BEAT_SECONDS = 1.6
XFADE_SECONDS = 0.3

# (name, slug, panel bbox in the PSD's native pixel coords, [new caption per beat])
# Panel boxes come from re-running segment_panels.py's own border-detection
# against the PSD composite (native res finds cleaner lines than the
# published 900px export, see docs/progress.md 2026-08-29) or, where that
# didn't cleanly segment (020_barney), a hand-picked crop around the
# confirmed swappable layer.
REMIXES = [
    ("001_the_funny_guy_ending", "001_the_funny_guy",
     (844, 1594, 1745, 2184), ["Season 1, out of an eventual 12."]),
    ("047_dinner_splash", "047_dinner",
     (0, 3, 2548, 988), [
         "The lease was up in fourteen minutes.",
         "I am legally a hat now.",
         "Local news at 11.",
     ]),
    ("047_dinner_ending", "047_dinner",
     (2173, 988, 2548, 1475), ["Koven & Repair Man are still technically registered voters. The End."]),
    ("020_barney_splat", "020_barney",
     (980, 370, 1375, 800), ["Compliance!"]),
    ("020_barney_potty", "020_barney",
     (1345, 755, 1705, 1150), ["We flushed it down the Senate!"]),
]


def bbox_inside(inner, outer) -> bool:
    ix0, iy0, ix1, iy1 = inner
    ox0, oy0, ox1, oy1 = outer
    cx, cy = (ix0 + ix1) / 2, (iy0 + iy1) / 2
    return ox0 <= cx <= ox1 and oy0 <= cy <= oy1


def clean_panel(psd: PSDImage, panel_bbox) -> "Image":
    hidden = []
    for layer in psd:
        if layer.kind == "type" and layer.visible and bbox_inside(layer.bbox, panel_bbox):
            layer.visible = False
            hidden.append(layer.name)
    if not hidden:
        print(f"  warning: no type layer found inside {panel_bbox} -- panel may still have its original text", file=sys.stderr)
    composite = psd.composite()
    for layer in psd:
        if layer.name in hidden:
            layer.visible = True
    return composite.crop(panel_bbox)


def assemble_clip(frame_paths: list[Path], out_path: Path):
    clip_dur = BEAT_SECONDS + XFADE_SECONDS
    n_frames = int(clip_dur * FPS)
    inputs = []
    for p in frame_paths:
        inputs += ["-loop", "1", "-t", f"{clip_dur:.3f}", "-i", str(p)]

    filter_parts = []
    for i in range(len(frame_paths)):
        filter_parts.append(
            f"[{i}:v]scale={CANVAS[0]}:{CANVAS[1]},"
            f"zoompan=z='min(1+({ZOOM_END}-1)*on/{n_frames},{ZOOM_END})':"
            f"d=1:s={CANVAS[0]}x{CANVAS[1]},"
            f"fps={FPS},format=yuv420p[v{i}]"
        )
    chain = "[v0]"
    offset = clip_dur - XFADE_SECONDS
    for i in range(1, len(frame_paths)):
        out_label = f"[x{i}]" if i < len(frame_paths) - 1 else "[vout]"
        filter_parts.append(f"{chain}[v{i}]xfade=transition=fade:duration={XFADE_SECONDS:.3f}:offset={offset:.3f}{out_label}")
        chain = out_label
        offset += clip_dur - XFADE_SECONDS

    if len(frame_paths) == 1:
        map_target, filter_complex = "[v0]", filter_parts[0]
    else:
        map_target, filter_complex = "[vout]", ";".join(filter_parts)

    cmd = [
        "ffmpeg", "-y", "-nostdin", *inputs,
        "-filter_complex", filter_complex, "-map", map_target,
        "-c:v", "h264_nvenc", "-pix_fmt", "yuv420p", str(out_path),
    ]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        cmd[cmd.index("h264_nvenc")] = "libx264"
        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode != 0:
            print(result.stderr[-4000:], file=sys.stderr)
            return False
    return True


def main():
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    psd_cache: dict[str, PSDImage] = {}

    for name, slug, panel_bbox, beats in REMIXES:
        print(f"{name}: {slug} {panel_bbox} ({len(beats)} beat(s))")
        if slug not in psd_cache:
            psd_cache[slug] = PSDImage.open(RAW_DIR / f"{slug}.psd")
        panel_img = clean_panel(psd_cache[slug], panel_bbox)

        with tempfile.TemporaryDirectory() as tmp:
            tmp = Path(tmp)
            src = tmp / "panel.png"
            panel_img.convert("RGB").save(src)

            frame_paths = []
            for i, caption in enumerate(beats):
                dst = tmp / f"frame_{i:02d}.png"
                letterbox(src, dst, caption)
                frame_paths.append(dst)

            out_path = OUT_DIR / f"{name}.mp4"
            if assemble_clip(frame_paths, out_path):
                print(f"  wrote {out_path}")
            else:
                print(f"  FAILED: {name}", file=sys.stderr)


if __name__ == "__main__":
    main()
